server:
  port: 8882


spring:
  application:
    name: example-springcloud-zuul


eureka:
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000

zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
    max-total-connections: 300
    max-per-route-connections: 150
  routes:
    api:
      path: /api/**
      serviceId: tender-api
    resource:
      path: /resource/**
      serviceId: tender-resource
    root:
      path: /**
      serviceId: tender-resource