server:
  port: 8762


spring:
  application:
    name: example-springcloud-zuul


eureka:
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${spring.cloud.client.ipaddress}:${server.port}
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    data:
      path: /data/**
      serviceId: example-springcloud-data
    api:
      path: /api/**
      serviceId: example-springcloud-client