server:
  port: 8881

eureka:
  instance:
    hostname: localhost
  server:
    response-cache-update-interval-ms: 30000
    response-cache-auto-expiration-in-seconds: 180
    eviction-interval-timer-in-ms: 30000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

